name: Build and deploy Node.js app to Azure Web App - interfacegamecard

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: interfacegamecard
  NODE_VERSION: '24.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          package-manager-cache: false

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Test application
        run: npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1EC92AAE88AD43518066CF4C40E9D73F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FE2B234AF8D4988984E48FB9F841E30 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4CF792A71A224802B2070BF506805A95 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: .
